// Static equivalents of the app's editorial components, using the same verified data.
export function editorialHtml({ base, link, esc, founder, copy }) {
  const external = 'target="_blank" rel="noreferrer"';
  const education = `<section class="education-list" id="education"><span class="section-label">Образование и квалификация</span>${founder.founderEducation.map(([year, school, detail]) => `<article><span>${esc(year)}</span><div><h2>${esc(school)}</h2><p>${esc(detail)}</p></div></article>`).join("")}<a class="source-link" href="${founder.founderSource}" ${external}>Посмотреть документы и полную информацию об образовании →</a></section>`;
  const science = `<section class="science-block" id="science"><span class="section-label">Научный подход</span><h2>Авторский метод и научная публикация</h2><p>Метод рассматривает взаимосвязь ресурсов личности и эмоциональной зрелости. С его теоретическими основами можно ознакомиться в научной статье Алёны Савиновой.</p><a class="scientific-article-link" href="${founder.scientificArticle}" ${external}><span>Международный научно-исследовательский журнал · № 5 (155), 2025</span><strong>Теоретические основы создания авторского метода формирования ресурсных систем личности</strong><span>Читать опубликованную статью · DOI: 10.60797/IRJ.2025.155.53 →</span></a><div class="science-reviews" id="reviews"><h3>Рецензии</h3><div class="science-grid">${founder.founderReviews.map((review) => `<a class="science-review-card" href="${review.href}" ${external}><h3>${esc(review.title)}</h3><p class="science-review-role">${esc(review.role)}</p><p>${esc(review.description)}</p><span>Открыть полную рецензию →</span></a>`).join("")}</div></div></section>`;
  const book = `<section class="book-block" id="book"><div><span class="section-label">Книга Алёны Савиновой</span><h2>«Жить ресурсно»</h2><p>Практические инструменты саморегуляции и самодиагностики: как замечать своё состояние, находить энергию и работать с внутренними ограничениями.</p><div class="book-actions"><a class="button" href="${founder.bookPage}" ${external}>Подробнее о книге →</a><a class="text-link" href="${founder.bookFragment}" ${external}>Читать бесплатный фрагмент →</a></div></div><a class="book-cover" href="${founder.bookPage}" ${external}><img src="${base}images/book-live-resource.png" width="1680" height="1189" alt="Книга Алёны Савиновой «Жить ресурсно»"></a></section>`;
  const biography = `<section class="editorial-split founder-bio" id="about-founder"><div><span class="section-label">Основатель центра</span><h2>Алёна Савинова</h2></div><div class="rich-copy"><ul>${founder.founderFacts.map((fact) => `<li>${esc(fact)}</li>`).join("")}</ul><a class="source-link" href="${founder.founderSource}" ${external}>Профиль в Практическом институте клинической психологии и психосоматики →</a></div></section>`;
  const teaser = `<section class="resource-test-teaser section-shell" id="resource-test"><div class="section-label">Первый шаг<br>к балансу</div><div class="resource-teaser-copy"><span class="eyebrow">Авторский тест Алёны Савиновой</span><h2>Тест на ресурсность</h2><p>Поймите, где сейчас хватает внутренней опоры, а каким сферам нужно больше внимания. Посмотрите пример результата и получите личную расшифровку.</p><a class="button" href="${link("test-na-resursnost")}">Пройти тест →</a></div></section>`;
  const test = `<section class="resource-test-intro editorial-split"><div><span class="section-label">Об авторском тесте</span><h2>Начните работать с ресурсом</h2></div><div class="rich-copy"><p>Когда энергия быстро восстанавливается, легче двигаться вперёд и сохранять баланс в разных сферах жизни.</p><p>По наблюдениям автора теста, при нестабильном уровне энергии одна сфера может процветать, пока другие остаются на минимуме. Это может проявляться как:</p><ul><li>Нехватка энергии</li><li>Трудности или нежелание заводить новые отношения</li><li>Проблемы на работе</li><li>Ощущение постоянного потока негатива</li></ul><p>Авторский тест помогает обсудить ваше состояние со специалистом и наметить работу с ресурсом.</p></div></section><section class="resource-result"><div class="resource-result-heading"><span class="section-label">Пример результата</span><h2>Как выглядит баланс ресурсов</h2><p>Предоставленный автором пример с общим результатом 85%. Это пример, а не ваш персональный результат.</p></div><a href="${base}images/resource-test-example.webp" ${external} aria-label="Открыть пример результата в полном размере"><img src="${base}images/resource-test-example.webp" width="1280" height="729" alt="Пример результата авторского теста по сферам ресурсов. Общий результат 85%."></a><p class="resource-note">Результаты авторского теста не являются медицинским диагнозом и не заменяют консультацию специалиста.</p></section><section class="resource-test-next" id="take-test"><span class="section-label">Личная обратная связь</span><h2>Получите расшифровку от автора</h2><p>Алёна Савинова поможет разобраться, как восстановить баланс энергии в разных сферах жизни.</p><a class="button" href="${esc(copy.resourceTestUrl || copy.resourceTestRequest)}" ${external}>Пройти тест →</a>${!copy.resourceTestUrl ? '<p class="resource-note">Кнопка открывает WhatsApp с запросом теста. Сам тест вам отправит специалист.</p>' : ""}</section>`;
  return { education, science, book, biography, teaser, test };
}
